config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'admin/mfa_qr'
  get 'admin/verify'
  post 'admin/authenticate'
  get 'admin/dashboard'

  root to: 'admin#verify'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/admin_controller.rb
# frozen_string_literal: true

class AdminController < ApplicationController
  http_basic_authenticate_with name: 'raging', password: 'tortoise'
  before_action :verify_mfa, only: :dashboard

  def mfa_qr
    qrcode = RQRCode::QRCode.new(totp.provisioning_uri('test@test.com'))

    svg = qrcode.as_svg(
      offset: 0,
      color: '000',
      shape_rendering: 'crispEdges',
      module_size: 6,
      standalone: true
    )

    IO.binwrite('public/github-qrcode.svg', svg.to_s)
  end

  def authenticate
    redirect_to admin_dashboard_path if valid_mfa?
  rescue ROTP::Base32::Base32Error
    redirect_to admin_verify_path
  end

  private

  def valid_mfa?
    session[:user_id] = SecureRandom.uuid if totp.verify(params[:mfa_token])
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def totp
    @rotp = ROTP::TOTP.new(Rails.application.credentials.rotp_token, issuer: 'Admin')
  end

  def verify_mfa
    raise StandardError unless session[:user_id].present?
  end
end

app/helpers/admin_helper.rb
# frozen_string_literal: true

module AdminHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/admin/dashboard.html.erb
<h1>Admin#dashboard</h1>
<table>
  <th>State ID</th>
  <th>State Name</th>
  <th>City Name</th>
  <tr>
    <td><span>15</span></td>
    <td><span><a href="states/1">California</a></span></td>
    <td><span>Mountain View</span></td>
  </tr>
  <tr>
    <td><span>14</span></td>
    <td><span><a href="states/1">California</a></span></td>
    <td><span>Burlingame</span></td>
  </tr>
  <tr>
    <td><span>12</span></td>
    <td><span><a href="states/2">New York</a></span></td>
    <td><span>Brooklyn</span></td>
  </tr>
</table>

app/views/admin/mfa_qr.html.erb
<object data="/github-qrcode.svg" type="image/svg+xml">
</object>

app/views/admin/verify.html.erb
<h1>MFA</h1>

<%= form_tag admin_authenticate_path, method: :post do %>
  <input type="text" name="mfa_token" placeholder="Input your auth code">
  <input type="submit" value="Submit">
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>